### ISSUE TITLE
$Permissions = (Get-Acl -Path $Identity.DistinguishedName).Access is broken

### ISSUE THREAD

**Issue by ckrueger1979** [oliveirt/cActiveDirectorySecurity#2]
This line is broken:
$Permissions = (Get-Acl -Path $Identity.DistinguishedName).Access is broken

```
        # enumerate permissions on the Active Directory Object
        try
        {
            Write-Verbose " Extracting Access Control List."
            #$Permissions = (Get-Acl -Path $Identity.DistinguishedName).Access # broken
            $Permissions = (Get-ACL "AD:$((Get-ADUser $Identity.DistinguishedName).distinguishedname)").access # fixed
        }
```

**Comment by oliveirt** [comment]
Hi ckruegerkpmg. Could you send me the command you are running and the error you are receiving please? The functions changes path to the AD: automatically so there shouldn't be any need to include AD: in the path. 

See line 192 for example:
`Set-Location ($PSDriveName + ":") -ErrorAction Stop`

**Comment by ckrueger1979** [comment]
Hi,

sorry I can't reproduce it. Probably I've messed up my AD-drive yesterday with something else and that was the result.
I think my bugreport is invalid and my "fix" is invalid, too. It wouldn't work for getting RootDSE

greetings
Carsten

PS: I really like the module. Top work.

**Comment by oliveirt** [comment]
Thanks Carsten - glad you're enjoying the module. Yeah the AD: drive can be a little funny I find - particularly if it the PowerShell session is left open for longer periods / or in and out of sleep mode on laptops.
